/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataView: typeof import('./src/components/data-view/DataView.vue')['default']
    MonthsDay: typeof import('./src/components/months-day/MonthsDay.vue')['default']
    SearchData: typeof import('./src/components/search/SearchData.vue')['default']
    SearchOptions: typeof import('./src/components/search/SearchOptions.vue')['default']
    SelectModal: typeof import('./src/components/side-bar/SelectModal.vue')['default']
    SettingModal: typeof import('./src/components/side-bar/SettingModal.vue')['default']
    SideBar: typeof import('./src/components/side-bar/SideBar.vue')['default']
    UnknownDate: typeof import('./src/components/unknowns/UnknownDate.vue')['default']
    UnknownURI: typeof import('./src/components/unknowns/UnknownURI.vue')['default']
    VHeader: typeof import('./src/components/header/VHeader.vue')['default']
    Years: typeof import('./src/components/years/Years.vue')['default']
  }
}
