/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataView: typeof import('./src/components/data-view/DataView.vue')['default']
    DeleteGroup: typeof import('./src/components/side-bar/DeleteGroup.vue')['default']
    DeleteItem: typeof import('./src/components/side-bar/DeleteItem.vue')['default']
    InsertItem: typeof import('./src/components/side-bar/InsertItem.vue')['default']
    RenameGroup: typeof import('./src/components/side-bar/RenameGroup.vue')['default']
    SearchData: typeof import('./src/components/search/SearchData.vue')['default']
    SearchOptions: typeof import('./src/components/search/SearchOptions.vue')['default']
    SelectModal: typeof import('./src/components/side-bar/SelectModal.vue')['default']
    SettingsModal: typeof import('./src/components/side-bar/SettingsModal.vue')['default']
    SideBar: typeof import('./src/components/side-bar/SideBar.vue')['default']
    UnknownDate: typeof import('./src/components/unknowns/UnknownDate.vue')['default']
    UnknownURL: typeof import('./src/components/unknowns/UnknownURL.vue')['default']
    VHeader: typeof import('./src/components/header/VHeader.vue')['default']
  }
}
