name = "rss-feed"
account_id = "689fc74db37d94d7bf42a5bbf4931407"
compatibility_date = "2024-09-21"
workers_dev = false
route = "rss.hitorinbc.com/*"
main = "workers-site/index.js"

[site]
bucket = "./dist"
