name: rss feed auto update

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
        pnpm-version: [7.1.7]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ matrix.pnpm-version }}
      
      - run: pnpm i
      - run: pnpm build
      
      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.CF_WORKERS_TOKEN }}
